SELECT p.ID, p.NAME
FROM PLACES p
INNER JOIN (
    SELECT DISTINCT(s.PLACE_ID)
    FROM SCHEDULES s, PLACE_REVIEWS r
    WHERE s.PLACE_ID = r.PLACE_ID AND date(s.SCHEDULED_AT) = '2019-01-06') AS rs ON rs.PLACE_ID = p.ID
ORDER BY p.ID ASC