/* [Level 4] */
SET @ROW := -1;
SELECT h.HOUR, COUNT(HOUR(outs.DATETIME)) AS COUNT
FROM (SELECT (@ROW := @ROW+1) as HOUR FROM ANIMAL_OUTS limit 24) as h
      LEFT JOIN ANIMAL_OUTS outs ON h.HOUR=HOUR(outs.DATETIME)
GROUP BY h.HOUR
ORDER BY h.HOUR ASC
